apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webhook-data
  namespace: openshift-adp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # storageClassName: ""  # Omit to use the cluster default StorageClass. Uncomment and set to override.

